package com.example.localization

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    HINDI("hi", "Hindi", "हिन्दी"),
    TAMIL("ta", "Tamil", "தமிழ்"),
    TELUGU("te", "Telugu", "తెలుగు"),
    KANNADA("kn", "Kannada", "ಕನ್ನಡ"),
    BENGALI("bn", "Bengali", "বাংলা"),
    MARATHI("mr", "Marathi", "मराठी"),
    GUJARATI("gu", "Gujarati", "ગુજરાતી"),
    MALAYALAM("ml", "Malayalam", "മലയാളം"),
    PUNJABI("pa", "Punjabi", "ਪੰਜਾਬੀ"),
    ODIA("or", "Odia", "ଓଡ଼ିଆ"),
    ASSAMESE("as", "Assamese", "অসমীয়া");

    companion object {
        fun fromCode(code: String): AppLanguage {
            return entries.firstOrNull { it.code.equals(code, ignoreCase = true) } ?: ENGLISH
        }
    }
}

object AppStrings {
    fun get(key: String, lang: AppLanguage): String {
        return translations[lang]?.get(key) ?: translations[AppLanguage.ENGLISH]?.get(key) ?: key
    }

    private val translations: Map<AppLanguage, Map<String, String>> = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_title" to "SadakRakshak",
            "app_tagline" to "Fixing India's Roads, Together",
            "nav_feed" to "Road Radar",
            "nav_report" to "Report Issue",
            "nav_drive" to "Auto-Spotter",
            "nav_my_posts" to "My Reports",
            "nav_notifications" to "Alerts",
            "nav_profile" to "Profile",
            "search_placeholder" to "Search locality, road, city or pin...",
            "filter_all" to "All Roads",
            "filter_reported" to "Reported",
            "filter_in_progress" to "Work Started",
            "filter_resolved" to "Repaired",
            "filter_critical" to "Critical",
            "switch_map" to "Radar Map",
            "switch_list" to "Feed List",
            "report_pothole_title" to "Report Pothole / Road Damage",
            "take_photo" to "Capture / Select Photo",
            "ai_verifying" to "AI Analyzing Road Damage...",
            "ai_verified" to "AI Verified Pothole",
            "ai_confidence" to "AI Confidence",
            "severity_minor" to "Minor Dip / Surface Crack",
            "severity_moderate" to "Moderate Pothole",
            "severity_severe" to "Severe Crater",
            "severity_critical" to "Hazardous Trench / Critical",
            "location_label" to "GPS Geotagged Location",
            "get_current_location" to "Detect My Location",
            "road_type_label" to "Road Classification",
            "road_national_highway" to "National Highway (NHAI)",
            "road_state_highway" to "State Highway (PWD)",
            "road_urban" to "Urban Main Road",
            "road_residential" to "Colony / Street",
            "road_flyover" to "Flyover / Bridge",
            "authority_assigned" to "Assigned Civic Authority",
            "duplicate_warning_title" to "Duplicate Pothole Nearby!",
            "duplicate_warning_desc" to "A similar pothole was already reported within {dist}m. You can upvote or continue.",
            "submit_report" to "Submit Road Report",
            "submit_offline_saved" to "Saved to Offline Sync Queue",
            "status_reported" to "Reported",
            "status_under_review" to "Under Review",
            "status_in_progress" to "Work Started",
            "status_resolved" to "Resolved & Fixed",
            "update_repair_status" to "Update Repair Status",
            "mark_work_started" to "Mark Work Started",
            "mark_completed" to "Mark Repaired & Completed",
            "upload_repair_photo" to "Attach Repair Proof Photo",
            "drive_mode_title" to "Auto-Spotter Drive Assist",
            "drive_mode_subtitle" to "Real-time Accelerometer & Gyroscope Pothole Detection",
            "start_monitoring" to "Start Drive Detection",
            "stop_monitoring" to "Stop Monitoring",
            "simulate_bump" to "Simulate Road Bump (Test)",
            "sensor_active" to "Sensors Active - Detecting Road Shocks",
            "gforce_level" to "Vertical G-Force Shock",
            "gyro_tilt" to "Gyroscope Angular Tilt",
            "auto_logged_count" to "Detections this Trip",
            "review_and_post" to "Review & Post Detected Potholes",
            "google_sign_in" to "Sign in with Google",
            "guest_mode" to "Browse as Citizen Guest",
            "signed_in_as" to "Citizen Reporter",
            "offline_banner_title" to "Offline Mode Active",
            "offline_banner_desc" to "Reports are saved locally and will auto-sync once connected.",
            "sync_now" to "Sync Now",
            "sync_pending_count" to "{count} pending sync",
            "select_language" to "Choose Language / भाषा चुनें",
            "upvote" to "Upvote",
            "upvoted" to "Upvoted",
            "confirm_fixed" to "Confirm Repaired",
            "share_report" to "Share with Authority"
        ),
        AppLanguage.HINDI to mapOf(
            "app_title" to "सड़क रक्षक",
            "app_tagline" to "सुरक्षित सड़कें, सशक्त भारत",
            "nav_feed" to "सड़क रडार",
            "nav_report" to "रिपोर्ट करें",
            "nav_drive" to "ऑटो-डिटेक्टर",
            "nav_my_posts" to "मेरी रिपोर्ट्स",
            "nav_notifications" to "सूचनाएं",
            "nav_profile" to "प्रोफ़ाइल",
            "search_placeholder" to "इलाका, सड़क या शहर खोजें...",
            "filter_all" to "सभी सड़कें",
            "filter_reported" to "दर्ज शिकायतें",
            "filter_in_progress" to "काम शुरू",
            "filter_resolved" to "मरम्मत पूर्ण",
            "filter_critical" to "अति गंभीर",
            "switch_map" to "रडार मैप",
            "switch_list" to "सूची देखें",
            "report_pothole_title" to "गड्ढे या टूटी सड़क की रिपोर्ट करें",
            "take_photo" to "फ़ोटो खींचें / चुनें",
            "ai_verifying" to "AI सड़क की जांच कर रहा है...",
            "ai_verified" to "AI सत्यापित गड्ढा",
            "ai_confidence" to "AI सटीकता",
            "severity_minor" to "छोटा गड्ढा / दरार",
            "severity_moderate" to "मध्यम गड्ढा",
            "severity_severe" to "बड़ा गड्ढा / खतरनाक",
            "severity_critical" to "गहरी खाई / अति गंभीर",
            "location_label" to "GPS जियोटैग स्थान",
            "get_current_location" to "वर्तमान स्थान खोजें",
            "road_type_label" to "सड़क का प्रकार",
            "road_national_highway" to "राष्ट्रीय राजमार्ग (NHAI)",
            "road_state_highway" to "राज्य राजमार्ग (PWD)",
            "road_urban" to "शहरी मुख्य सड़क (Nagar Nigam)",
            "road_residential" to "कॉलोनी / स्थानीय सड़क",
            "road_flyover" to "फ्लाईओवर / पुल",
            "authority_assigned" to "संबंधित नगर निगम / प्राधिकरण",
            "duplicate_warning_title" to "पास में पहले से दर्ज गड्ढा मिला!",
            "duplicate_warning_desc" to "यह गड्ढा {dist} मीटर के दायरे में पहले से दर्ज है। आप समर्थन दे सकते हैं।",
            "submit_report" to "रिपोर्ट सबमिट करें",
            "submit_offline_saved" to "ऑफ़लाइन कतार में सहेजा गया",
            "status_reported" to "दर्ज हुआ",
            "status_under_review" to "समीक्षा जारी",
            "status_in_progress" to "कार्य प्रगति पर",
            "status_resolved" to "सड़क मरम्मत पूर्ण",
            "update_repair_status" to "मरम्मत की स्थिति अपडेट करें",
            "mark_work_started" to "कार्य प्रारंभ दर्ज करें",
            "mark_completed" to "सड़क ठीक हो गई",
            "upload_repair_photo" to "मरम्मत का प्रमाण फ़ोटो जोड़ें",
            "drive_mode_title" to "सवारी के दौरान ऑटो-डिटेक्शन",
            "drive_mode_subtitle" to "एक्सेलेरोमीटर और जायरोस्कोप सेंसर आधारित पहचान",
            "start_monitoring" to "ड्राइव निगरानी शुरू करें",
            "stop_monitoring" to "निगरानी रोकें",
            "simulate_bump" to "सड़क झटका सिम्युलेट करें (टेस्ट)",
            "sensor_active" to "सेंसर चालू हैं - झटके दर्ज हो रहे हैं",
            "gforce_level" to "जी-फोर्स झटका स्तर",
            "gyro_tilt" to "जायरोस्कोप झुकाव",
            "auto_logged_count" to "इस यात्रा में मिले गड्ढे",
            "review_and_post" to "दर्ज गड्ढों की जांच व पोस्ट करें",
            "google_sign_in" to "Google से साइन इन करें",
            "guest_mode" to "अतिथि नागरिक के रूप में ब्राउज़ करें",
            "signed_in_as" to "सचेत नागरिक",
            "offline_banner_title" to "ऑफ़लाइन मोड सक्रिय",
            "offline_banner_desc" to "इंटरनेट आने पर डेटा स्वतः सिंक हो जाएगा।",
            "sync_now" to "अभी सिंक करें",
            "sync_pending_count" to "{count} रिपोर्ट्स सिंक बाकी",
            "select_language" to "भाषा चुनें / Select Language",
            "upvote" to "समर्थन दें",
            "upvoted" to "समर्थित",
            "confirm_fixed" to "मरम्मत की पुष्टि करें",
            "share_report" to "अधिकारियों को भेजें"
        ),
        AppLanguage.TAMIL to mapOf(
            "app_title" to "சடக்ரக்ஷக்",
            "app_tagline" to "பாதுகாப்பான சாலைகள் நம் உரிமை",
            "nav_feed" to "சாலை ரேடார்",
            "nav_report" to "புகார் செய்",
            "nav_drive" to "தானியங்கி கண்டுபிடிப்பு",
            "nav_my_posts" to "என் பதிவுகள்",
            "nav_notifications" to "அறிவிப்புகள்",
            "nav_profile" to "சுயவிவரம்",
            "search_placeholder" to "பகுதி அல்லது சாலையைத் தேடுங்கள்...",
            "filter_all" to "அனைத்து சாலைகள்",
            "filter_reported" to "பதிவானவை",
            "filter_in_progress" to "வேலை நடக்கிறது",
            "filter_resolved" to "சரியானது",
            "filter_critical" to "ஆபத்தானது",
            "switch_map" to "வரைபடம்",
            "switch_list" to "பட்டியல்",
            "report_pothole_title" to "குழிகள் / சேதமடைந்த சாலையைப் புகாரளிக்கவும்",
            "take_photo" to "புகைப்படம் எடுக்கவும்",
            "ai_verifying" to "AI சாலைப் புகைப்படத்தை ஆய்வு செய்கிறது...",
            "ai_verified" to "AI உறுதிப்படுத்திய குழி",
            "ai_confidence" to "AI துல்லியம்",
            "severity_minor" to "சிறிய விரிசல்",
            "severity_moderate" to "நடுத்தர குழி",
            "severity_severe" to "பெரிய குழி",
            "severity_critical" to "ஆபத்தான பள்ளம்",
            "location_label" to "GPS இடம்",
            "get_current_location" to "என் இருப்பிடம்",
            "submit_report" to "புகாரை சமர்ப்பிக்கவும்",
            "google_sign_in" to "Google மூலம் உள்நுழையவும்",
            "guest_mode" to "விருந்தினராக தொடரவும்",
            "select_language" to "மொழியைத் தேர்வு செய்யவும்"
        ),
        AppLanguage.TELUGU to mapOf(
            "app_title" to "సడక్ రక్షక్",
            "app_tagline" to "రహదారుల భద్రత మన బాధ్యత",
            "nav_feed" to "రోడ్ రాడార్",
            "nav_report" to "ఫిర్యాదు చేయండి",
            "nav_drive" to "ఆటో-గుర్తింపు",
            "nav_my_posts" to "నా నివేదికలు",
            "nav_notifications" to "నోటిఫికేషన్లు",
            "nav_profile" to "ప్రొఫైల్",
            "search_placeholder" to "ప్రాంతం లేదా రహదారిని శోధించండి...",
            "report_pothole_title" to "రోడ్డు గుంతల ఫిర్యాదు",
            "take_photo" to "ఫోటో తీయండి",
            "submit_report" to "ఫిర్యాదును సమర్పించండి",
            "google_sign_in" to "Googleతో సైన్ ఇన్ చేయండి",
            "guest_mode" to "అతిథిగా కొనసాగండి",
            "select_language" to "భాషను ఎంచుకోండి"
        ),
        AppLanguage.KANNADA to mapOf(
            "app_title" to "ಸಡಕ್ ರಕ್ಷಕ್",
            "app_tagline" to "ಸುರಕ್ಷಿತ ರಸ್ತೆಗಳು ನಮ್ಮ ಹಕ್ಕು",
            "nav_feed" to "ರಸ್ತೆ ರೇಡಾರ್",
            "nav_report" to "ವರದಿ ಮಾಡಿ",
            "nav_drive" to "ಸ್ವಯಂಚಾಲಿತ ಪತ್ತೆ",
            "nav_my_posts" to "ನನ್ನ ವರದಿಗಳು",
            "nav_notifications" to "ಸೂಚನೆಗಳು",
            "nav_profile" to "ಪ್ರೊಫೈಲ್",
            "search_placeholder" to "ಪ್ರದೇಶ, ರಸ್ತೆ ಹುಡುಕಿ...",
            "report_pothole_title" to "ರಸ್ತೆ ಗುಂಡಿ ವರದಿ ಮಾಡಿ",
            "take_photo" to "ಫೋಟೋ ತೆಗೆಯಿರಿ",
            "submit_report" to "ವರದಿ ಸಲ್ಲಿಸಿ",
            "google_sign_in" to "Google ನೊಂದಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ",
            "guest_mode" to "ಅತಿಥಿಯಾಗಿ ವೀಕ್ಷಿಸಿ",
            "select_language" to "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ"
        ),
        AppLanguage.BENGALI to mapOf(
            "app_title" to "সড়ক রক্ষক",
            "app_tagline" to "নিরাপদ সড়ক গড়ার অঙ্গীকার",
            "nav_feed" to "রোড রাডার",
            "nav_report" to "রিপোর্ট করুন",
            "nav_drive" to "অটো ডিটেক্টর",
            "nav_my_posts" to "আমার রিপোর্ট",
            "nav_notifications" to "বিজ্ঞপ্তি",
            "nav_profile" to "প্রোফাইল",
            "search_placeholder" to "এলাকা বা রাস্তা খুঁজুন...",
            "report_pothole_title" to "গর্ত বা ভাঙা রাস্তার রিপোর্ট",
            "take_photo" to "ছবি তুলুন",
            "submit_report" to "জমা দিন",
            "google_sign_in" to "Google দিয়ে সাইন ইন করুন",
            "guest_mode" to "অতিথি হিসেবে ব্রাউজ করুন",
            "select_language" to "ভাষা নির্বাচন করুন"
        ),
        AppLanguage.MARATHI to mapOf(
            "app_title" to "सडक रक्षक",
            "app_tagline" to "सुरक्षित रस्ते, आपली जबाबदारी",
            "nav_feed" to "रस्ता रडार",
            "nav_report" to "तक्रार नोंदवा",
            "nav_drive" to "ऑटो-डिटेक्टर",
            "nav_my_posts" to "माझ्या नोंदी",
            "nav_notifications" to "सूचना",
            "nav_profile" to "प्रोफाइल",
            "search_placeholder" to "परिसर किंवा रस्ता शोधा...",
            "report_pothole_title" to "खड्डे व रस्त्यांची तक्रार",
            "take_photo" to "फोटो काढा",
            "submit_report" to "तक्रार सादर करा",
            "google_sign_in" to "Google सह साइन इन करा",
            "guest_mode" to "अतिथी म्हणून पहा",
            "select_language" to "भाषा निवडा"
        ),
        AppLanguage.GUJARATI to mapOf(
            "app_title" to "સડક રક્ષક",
            "app_tagline" to "સુરક્ષિત રસ્તાઓ, આપણો અધિકાર",
            "nav_feed" to "રોડ રડાર",
            "nav_report" to "ફરિયાદ કરો",
            "nav_drive" to "ઓટો ડિટેક્ટર",
            "nav_my_posts" to "મારી ફરિયાદો",
            "nav_notifications" to "સૂચનાઓ",
            "nav_profile" to "પ્રોફાઇલ",
            "search_placeholder" to "વિસ્તાર કે રસ્તો શોધો...",
            "report_pothole_title" to "ખાડા અને ખરાબ રસ્તાની ફરિયાદ",
            "take_photo" to "ફોટો લો",
            "submit_report" to "સબમિટ કરો",
            "google_sign_in" to "Google દ્વારા સાઇન ઇન કરો",
            "guest_mode" to "ગેસ્ટ તરીકે આગળ વધો",
            "select_language" to "ભાષા પસંદ કરો"
        ),
        AppLanguage.MALAYALAM to mapOf(
            "app_title" to "സഡക് രക്ഷക്",
            "app_tagline" to "സുരക്ഷിത പാതകൾ നമ്മുടെ അവകാശം",
            "nav_feed" to "റോഡ് റഡാർ",
            "nav_report" to "പരാതിപ്പെടുക",
            "nav_drive" to "ഓട്ടോ ഡിറ്റക്ടർ",
            "nav_my_posts" to "എന്റെ പോസ്റ്റുകൾ",
            "nav_notifications" to "അറിയിപ്പുകൾ",
            "nav_profile" to "പ്രൊഫൈൽ",
            "search_placeholder" to "സ്ഥലം അല്ലെങ്കിൽ റോഡ് തിരയുക...",
            "report_pothole_title" to "റോഡിലെ കുഴികൾ റിപ്പോർട്ട് ചെയ്യുക",
            "take_photo" to "ഫോട്ടോ എടുക്കുക",
            "submit_report" to "സമർപ്പിക്കുക",
            "google_sign_in" to "Google ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക",
            "guest_mode" to "അതിഥിയായി തുടരുക",
            "select_language" to "ഭാഷ തിരഞ്ഞെടുക്കുക"
        ),
        AppLanguage.PUNJABI to mapOf(
            "app_title" to "ਸੜਕ ਰੱਖਿਅਕ",
            "app_tagline" to "ਸੁਰੱਖਿਅਤ ਸੜਕਾਂ ਸਾਡਾ ਹੱਕ",
            "nav_feed" to "ਸੜਕ ਰਡਾਰ",
            "nav_report" to "ਰਿਪੋਰਟ ਕਰੋ",
            "nav_drive" to "ਆਟੋ ਡਿਟੈਕਟਰ",
            "nav_my_posts" to "ਮੇਰੀਆਂ ਰਿਪੋਰਟਾਂ",
            "nav_notifications" to "ਸੂਚਨਾਵਾਂ",
            "nav_profile" to "ਪ੍ਰੋਫਾਈਲ",
            "search_placeholder" to "ਇਲਾਕਾ ਜਾਂ ਸੜਕ ਲੱਭੋ...",
            "report_pothole_title" to "ਖੱਡਿਆਂ ਦੀ ਰਿਪੋਰਟ ਕਰੋ",
            "take_photo" to "ਫੋਟੋ ਖਿੱਚੋ",
            "submit_report" to "ਜਮ੍ਹਾਂ ਕਰੋ",
            "google_sign_in" to "Google ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ",
            "guest_mode" to "ਮਹਿਮਾਨ ਵਜੋਂ ਦੇਖੋ",
            "select_language" to "ਭਾਸ਼ਾ ਚੁਣੋ"
        ),
        AppLanguage.ODIA to mapOf(
            "app_title" to "ସଡ଼କ ରକ୍ଷକ",
            "app_tagline" to "ସୁରକ୍ଷିତ ରାସ୍ତା ଆମର ଅଧିକାର",
            "nav_feed" to "ରୋଡ଼ ରାଡାର",
            "nav_report" to "ରିପୋର୍ଟ କରନ୍ତୁ",
            "nav_drive" to "ଅଟୋ ଡିଟେକ୍ଟର",
            "nav_my_posts" to "ମୋର ରିପୋର୍ଟ",
            "nav_notifications" to "ବିଜ୍ଞପ୍ତି",
            "nav_profile" to "ପ୍ରୋଫାଇଲ",
            "search_placeholder" to "ସ୍ଥାନ କିମ୍ବା ରାସ୍ତା ଖୋଜନ୍ତୁ...",
            "report_pothole_title" to "ଖାଲଖମା ରିପୋର୍ଟ କରନ୍ତୁ",
            "take_photo" to "ଫଟୋ ଉଠାନ୍ତୁ",
            "submit_report" to "ଦାଖଲ କରନ୍ତୁ",
            "google_sign_in" to "Google ରେ ସାଇନ ଇନ କରନ୍ତୁ",
            "guest_mode" to "ଅତିଥି ଭାବେ ବ୍ରାଉଜ କରନ୍ତୁ",
            "select_language" to "ଭାଷା ବାଛନ୍ତୁ"
        ),
        AppLanguage.ASSAMESE to mapOf(
            "app_title" to "সড়ক ৰক্ষক",
            "app_tagline" to "সুৰক্ষিত পথ আমাৰ অধিকাৰ",
            "nav_feed" to "ৰোড ৰাডাৰ",
            "nav_report" to "ৰিপোৰ্ট কৰক",
            "nav_drive" to "অট' ডিটেক্টৰ",
            "nav_my_posts" to "মোৰ ৰিপোৰ্ট",
            "nav_notifications" to "জাননী",
            "nav_profile" to "প্ৰফাইল",
            "search_placeholder" to "স্থান বা পথ সন্ধান কৰক...",
            "report_pothole_title" to "পথৰ গাঁতৰ ৰিপোৰ্ট দিয়ক",
            "take_photo" to "ছবি তোলক",
            "submit_report" to "জমা দিয়ক",
            "google_sign_in" to "Google ৰ সৈতে ছাইন ইন কৰক",
            "guest_mode" to "অতিথি হিচাপে চাওক",
            "select_language" to "ভাষা বাছক"
        )
    )
}
